import { makeStyles } from "@fluentui/react-components";
import type { Tone } from "./status";

export const useDesktopStyles = makeStyles({
  appFrame: {
    width: "100vw",
    height: "100vh",
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    overflow: "hidden",
    backgroundColor: "#f5f6f8",
  },
  shell: {
    width: "100%",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    display: "grid",
    gridTemplateColumns: "250px clamp(440px, 34vw, 660px) minmax(520px, 1fr)",
    backgroundColor: "#f5f6f8",
    color: "#1f2428",
  },
  sidebar: {
    minHeight: 0,
    borderRight: "1px solid #d9dee7",
    backgroundColor: "#fbfbfc",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
  },
  sidebarHeader: {
    padding: "18px 18px 12px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "start",
    gap: "12px",
  },
  brandBlock: {
    display: "grid",
    gap: "2px",
    minWidth: 0,
  },
  brandTitle: {
    lineHeight: "30px",
    letterSpacing: "0",
  },
  scrollPane: {
    minHeight: 0,
    minWidth: 0,
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "auto",
    scrollbarGutter: "stable",
    outline: "none",
  },
  projectList: {
    minHeight: 0,
    padding: "4px 10px 10px",
    display: "grid",
    alignContent: "start",
    gap: "6px",
  },
  projectRow: {
    width: "100%",
    minHeight: "68px",
    padding: "9px 10px 9px 12px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: "7px",
    textAlign: "left",
    border: "1px solid transparent",
    borderLeft: "3px solid transparent",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
  },
  projectRowHover: {
    ":hover": {
      backgroundColor: "#f0f3f7",
      border: "1px solid #e2e7ef",
      borderLeftColor: "#a9b7ca",
    },
    ":focus-visible": {
      outline: "2px solid #0f6cbd",
      outlineOffset: "1px",
    },
  },
  projectRowSelected: {
    backgroundColor: "#eef5fc",
    border: "1px solid #b9d5f0",
    borderLeftColor: "#0f6cbd",
  },
  projectTitleLine: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "center",
    minWidth: 0,
  },
  projectMetaLine: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: "2px",
    minWidth: 0,
  },
  countLine: {
    display: "flex",
    gap: "5px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  sidebarFooter: {
    padding: "10px 14px 14px",
    borderTop: "1px solid #e6e9ee",
  },
  centerColumn: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
  },
  centerHeader: {
    minWidth: 0,
    padding: "16px 20px 10px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: "6px",
    alignItems: "start",
    borderBottom: "1px solid #e2e6ec",
    backgroundColor: "#f8f9fb",
  },
  pageTitle: {
    lineHeight: "30px",
    letterSpacing: "0",
  },
  centerScroll: {
    minHeight: 0,
    padding: "12px 20px 18px",
  },
  detailColumn: {
    minHeight: 0,
    position: "relative",
    borderLeft: "1px solid #d9dee7",
    backgroundColor: "#fbfbfc",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    overflow: "hidden",
  },
  detailHeader: {
    padding: "18px 22px 12px",
    borderBottom: "1px solid #e2e6ec",
    display: "grid",
    gap: "8px",
  },
  detailTitleLine: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "10px",
    alignItems: "center",
  },
  detailScroll: {
    minHeight: 0,
    padding: "14px 18px 22px",
    display: "grid",
    gridTemplateRows: "minmax(240px, 1fr) minmax(150px, auto)",
    alignContent: "stretch",
    gap: "12px",
  },
  compactToolbar: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexWrap: "wrap",
  },
  introStrip: {
    minHeight: "44px",
    padding: "8px 10px",
    border: "1px solid #dfe5ee",
    borderRadius: "6px",
    backgroundColor: "#ffffff",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    gap: "10px",
    alignItems: "start",
  },
  introContent: {
    display: "grid",
    gap: "4px",
    minWidth: 0,
  },
  introSteps: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px 18px",
  },
  summaryBar: {
    marginTop: "10px",
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    border: "1px solid #dfe5ee",
    borderRadius: "6px",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  summaryItem: {
    minHeight: "58px",
    padding: "9px 12px",
    display: "grid",
    gap: "3px",
    borderRight: "1px solid #edf0f4",
  },
  panel: {
    marginTop: "10px",
    border: "1px solid #dfe5ee",
    borderRadius: "6px",
    backgroundColor: "#ffffff",
    boxShadow: "0 1px 2px rgba(15, 23, 42, 0.06)",
  },
  panelHeader: {
    padding: "11px 12px",
    display: "grid",
    gap: "2px",
    borderBottom: "1px solid #edf0f4",
  },
  actionList: {
    display: "grid",
  },
  actionRow: {
    width: "100%",
    minHeight: "54px",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    gap: "10px",
    alignItems: "center",
    padding: "9px 12px",
    border: "0",
    borderBottom: "1px solid #edf0f4",
    backgroundColor: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
    ":hover": {
      backgroundColor: "#f7f9fb",
    },
    ":focus-visible": {
      outline: "2px solid #0f6cbd",
      outlineOffset: "-2px",
    },
  },
  actionRowSelected: {
    backgroundColor: "#eef5fc",
    boxShadow: "inset 3px 0 0 #0f6cbd",
  },
  settingsPanel: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    zIndex: 7,
    width: "min(100%, 420px)",
    borderLeft: "1px solid #d9dee7",
    backgroundColor: "#ffffff",
    boxShadow: "-14px 0 24px rgba(15, 23, 42, 0.12)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
  },
  settingHeader: {
    padding: "16px 18px",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "center",
    borderBottom: "1px solid #edf0f4",
  },
  settingsGrid: {
    display: "grid",
    alignContent: "start",
    gap: "0",
    minHeight: 0,
    minWidth: 0,
    overflowY: "auto",
    overflowX: "hidden",
    scrollbarGutter: "stable",
  },
  settingRow: {
    minHeight: "58px",
    padding: "9px 12px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "12px",
    alignItems: "center",
  },
  emptyState: {
    minHeight: "120px",
    display: "grid",
    placeItems: "center",
    padding: "18px",
    textAlign: "center",
    color: "#667085",
  },
  statusPill: {
    minWidth: "44px",
    height: "22px",
    padding: "0 8px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "999px",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  toneSuccess: {
    color: "#0b6b19",
    backgroundColor: "#e6f4ea",
  },
  toneWarning: {
    color: "#8a5a00",
    backgroundColor: "#fff4ce",
  },
  toneDanger: {
    color: "#b42318",
    backgroundColor: "#fee4e2",
  },
  toneNeutral: {
    color: "#344054",
    backgroundColor: "#eef2f6",
  },
  countPill: {
    height: "22px",
    padding: "0 7px",
    display: "inline-flex",
    alignItems: "center",
    border: "1px solid #d5dce7",
    borderRadius: "999px",
    color: "#344054",
    backgroundColor: "#ffffff",
    fontSize: "12px",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  ellipsis: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  muted: {
    color: "#667085",
  },
  small: {
    fontSize: "12px",
    lineHeight: "18px",
  },
  operationStatusBar: {
    minHeight: "34px",
    padding: "5px 14px",
    display: "grid",
    gridTemplateColumns: "18px minmax(0, 1fr)",
    gap: "8px",
    alignItems: "center",
    borderTop: "1px solid #d9dee7",
    color: "#344054",
    backgroundColor: "#ffffff",
  },
  operationStatusIndicator: {
    width: "18px",
    height: "18px",
    display: "grid",
    placeItems: "center",
    borderRadius: "999px",
    backgroundColor: "#d5dce7",
    "::before": {
      content: '""',
      width: "7px",
      height: "7px",
      borderRadius: "999px",
      backgroundColor: "currentColor",
    },
  },
  operationStatusIndicatorPending: {
    backgroundColor: "transparent",
    "::before": {
      content: "none",
    },
  },
  operationStatusText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  operationStatusIdle: {
    color: "#475467",
    backgroundColor: "#ffffff",
  },
  operationStatusPending: {
    color: "#0f6cbd",
    backgroundColor: "#f5f9ff",
  },
  operationStatusSuccess: {
    color: "#0b6b19",
    backgroundColor: "#f6fbf7",
  },
  operationStatusCancelled: {
    color: "#667085",
    backgroundColor: "#fafbfc",
  },
  operationStatusDanger: {
    color: "#b42318",
    backgroundColor: "#fff8f7",
  },
});

export function toneClass(
  styles: ReturnType<typeof useDesktopStyles>,
  tone: Tone,
): string {
  return {
    success: styles.toneSuccess,
    warning: styles.toneWarning,
    danger: styles.toneDanger,
    neutral: styles.toneNeutral,
  }[tone];
}

export function cx(...classes: Array<string | false | undefined>): string {
  return classes.filter(Boolean).join(" ");
}
