import { makeStyles } from "@fluentui/react-components";

export const useDetailStyles = makeStyles({
  tablePanel: {
    border: "1px solid #dfe5ee",
    borderRadius: "6px",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  cartridgePanel: {
    minHeight: "300px",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
  },
  untrackedPanel: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, auto)",
  },
  tableHeader: {
    padding: "10px 12px 8px",
    display: "grid",
    gap: "2px",
    borderBottom: "1px solid #edf0f4",
  },
  cartridgeListViewport: {
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "auto",
    scrollbarGutter: "stable",
  },
  cartridgeGrid: {
    display: "grid",
  },
  cartridgeHeaderRow: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    minHeight: "34px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 64px minmax(140px, auto) 58px",
    gap: "10px",
    alignItems: "center",
    padding: "0 12px",
    borderBottom: "1px solid #e5e9ef",
    backgroundColor: "#fafbfc",
    color: "#667085",
    fontSize: "12px",
    fontWeight: 600,
  },
  cartridgeRow: {
    width: "100%",
    minHeight: "52px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 64px minmax(140px, auto) 58px",
    gap: "10px",
    alignItems: "center",
    padding: "7px 12px",
    border: "0",
    borderBottom: "1px solid #edf0f4",
    backgroundColor: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
    ":hover": { backgroundColor: "#f7f9fb" },
    ":focus-visible": {
      outline: "2px solid #0f6cbd",
      outlineOffset: "-2px",
    },
  },
  cartridgeRowSelected: {
    backgroundColor: "#eef5fc",
    boxShadow: "inset 3px 0 0 #0f6cbd",
  },
  cartridgeNameCell: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: "22px",
  },
  cartridgeMetricSummary: {
    minWidth: 0,
    color: "#5f6b7a",
    fontSize: "12px",
    fontVariantNumeric: "tabular-nums",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  metricCell: {
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
  },
  tableButton: {
    minWidth: "46px",
    height: "30px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  pathCell: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  untrackedList: {
    minHeight: 0,
    maxHeight: "260px",
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "auto",
    scrollbarGutter: "stable",
    display: "grid",
  },
  fileRow: {
    minHeight: "54px",
    padding: "9px 12px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "center",
    border: "0",
    borderBottom: "1px solid #edf0f4",
    backgroundColor: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
    ":hover": { backgroundColor: "#f7f9fb" },
    ":focus-visible": {
      outline: "2px solid #0f6cbd",
      outlineOffset: "-2px",
    },
  },
  fileRowSelected: {
    backgroundColor: "#eef5fc",
    boxShadow: "inset 3px 0 0 #0f6cbd",
  },
  drawerPanel: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    zIndex: 6,
    width: "min(100%, 560px)",
    borderLeft: "1px solid #d9dee7",
    backgroundColor: "#ffffff",
    boxShadow: "-14px 0 24px rgba(15, 23, 42, 0.12)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
  },
  drawerHeader: {
    padding: "14px 16px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "10px",
    alignItems: "start",
    borderBottom: "1px solid #edf0f4",
  },
  drawerContent: {
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "auto",
    scrollbarGutter: "stable",
    padding: "12px 16px 18px",
    display: "grid",
    alignContent: "start",
    gap: "12px",
  },
  drawerSection: {
    display: "grid",
    gap: "6px",
  },
  fileList: {
    display: "grid",
    gap: "4px",
  },
  fileListItem: {
    minHeight: "32px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "center",
    padding: "6px 8px",
    border: "1px solid #edf0f4",
    borderRadius: "6px",
    backgroundColor: "#fafbfc",
  },
  sectionActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
});
